# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jF2JJRORbB8BXyLTzWRHAzBht4dPYxsY
"""

def selection_sort(arr):
  for i in range(len(arr)):
    for j in range(1, len(arr)-1):
      if j<i:
        arr[j], arr[i] = arr[i], arr[j]
  return arr

selection_sort([5,4,3,2,1])

def selection_sort(arr):
    n = len(arr)
    for i in range(0, n):
        minvalue = arr[i]
        minindex = i
        for j in range(i+1, n):
            if arr[j] < minvalue:
                minvalue = arr[j]
                minindex = j
        arr[i], arr[minindex] = arr[minindex], arr[i]
    return arr
selection_sort([5, 4, 3, 2, 1])

for i in range(0, 5):
    print(i)

